baseURL: "https://bttuliao.github.io/"
languageCode: en-us
title: Bianca Tuliao
theme: PaperMod

markup:
  goldmark:
    renderer:
      unsafe: true

pluralizelisttitles: "false"

params:
  ShowReadingTime: true
  dateFormat: "January 2, 2006"
  description: The blog of Bianca Tuliao, Software Engineer based in Philadelphia
  assets:
    disableFingerprinting: true
  homeInfoParams:
    Title: "Welcome 👋"
    Content: "
              My name is Bianca and I'm a software engineer from Philadelphia. Most recently, I was a software engineer at QVC and built applications within the supply chain domain.
              I graduated from Temple University with a Bachelor of Science in [Information Science and Technology](https://www.temple.edu/academics/degree-programs/information-science-and-technology-major-st-ist-bs).
             <br /> <br />I grew up in the 'burbs of Chicago and am a big fan of Lou Malnati's for deep dish pizza. I enjoy watching Esports and solving puzzles from [Puzzled Pint](http://puzzledpint.com/). When I'm not at my computer I'm most likely making coffee,
             reading, or crocheting.
            "
  
  socialIcons:
    - name: github
      url: "https://github.com/bttuliao"
    - name: linkedin
      url: "https://www.linkedin.com/in/biancatuliao/"
    - name: email
      url: mailto:btuliaodev@gmail.com
    - name: goodreads
      url: "https://www.goodreads.com/user/show/115285117-bianca"
      
menu:
  main:
    - identifier: About
      name: About
      url: 
      weight: 10
    - identifier: Career
      name: Career
      url: /career/
      weight: 20
    - identifier: Blog
      name: Blog
      url: /blog/
      weight: 30