baseURL: "https://bttuliao.github.io/"
languageCode: en-us
title: Bianca Tuliao
theme: PaperMod

markup:
  goldmark:
    renderer:
      unsafe: true

pluralizelisttitles: "false"

params:
  ShowReadingTime: true
  dateFormat: "January 2, 2006"
  description: The blog of Bianca Tuliao, Software Engineer based in Chicago
  assets:
    disableFingerprinting: true
  profileMode:
    enabled: true
    title: "Bianca Tuliao"
    subtitle: "Software engineer based in Chicago. Previously from Philadelphia"
    imageUrl: "/profilepic.png" # optional
    imageTitle: "Bianca Tuliao" # optional
    imageWidth: 130 # custom size
    imageHeight: 130 # custom size

  socialIcons:
    - name: github
      url: "https://github.com/bttuliao"
    - name: linkedin
      url: "https://www.linkedin.com/in/biancatuliao/"
    - name: email
      url: mailto:btuliaodev@gmail.com
    - name: goodreads
      url: "https://www.goodreads.com/user/show/115285117-bianca"
      
menu:
  main:
    - identifier: Home
      name: Home
      url: 
      weight: 10
    - identifier: About
      name: About
      url: /about/
      weight: 20
    - identifier: Career
      name: Career
      url: /career/
      weight: 30
    - identifier: Projects
      name: Projects
      url: /projects/
      weight: 40
    - identifier: Blog
      name: Blog
      url: /blog/
      weight: 50
